-- ============ DR Code Schema ============
-- شغّل هذا الملف يدوياً في Supabase SQL Editor قبل أول تشغيل.
-- المفتاح الأساسي bigint generated by default as identity حتى يُحافظ على الـ IDs القديمة في الترحيل.
-- الملف آمن لإعادة التنفيذ (create table if not exists).

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  username text,
  phone text unique not null,
  grade text not null,
  role text not null default 'student',
  subscription boolean not null default false,
  blocked boolean not null default false,
  password_hash text not null,
  created_at bigint not null
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  title_en text not null default '',
  description text not null default '',
  description_en text not null default '',
  image text not null default '',
  grade text not null default 'all',
  "order" integer not null default 0,
  created_at bigint not null
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade,
  title text not null,
  title_en text not null default '',
  video_type text not null default 'youtube',
  video_url text not null default '',
  duration integer not null default 0,
  description text not null default '',
  description_en text not null default '',
  grade text not null default 'all',
  "order" integer not null default 0,
  created_at bigint not null
);

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete set null,
  title text not null,
  title_en text not null default '',
  time_limit integer,
  passing_score integer not null default 50,
  grade text not null default 'all',
  allow_retake boolean not null default false,
  "order" integer not null default 0,
  created_at bigint not null
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  exam_id bigint references public.exams(id) on delete cascade,
  text text not null,
  text_en text not null default '',
  options jsonb not null default '[]',
  correct_index integer not null default 0,
  image text not null default '',
  "order" integer not null default 0
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete set null,
  title text not null,
  title_en text not null default '',
  body text not null default '',
  body_en text not null default '',
  image text not null default '',
  grade text not null default 'all',
  "order" integer not null default 0,
  created_at bigint not null
);

create table if not exists public.top_students (
  id bigint generated by default as identity primary key,
  name text not null,
  image text not null default '',
  rank integer not null default 1,
  grade text not null,
  created_at bigint not null
);

create table if not exists public.progress (
  user_id bigint references public.users(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete cascade,
  seconds_watched integer not null default 0,
  completed boolean not null default false,
  updated_at bigint not null,
  primary key (user_id, lesson_id)
);

create table if not exists public.exam_results (
  user_id bigint references public.users(id) on delete cascade,
  exam_id bigint references public.exams(id) on delete cascade,
  best integer not null default 0,
  score integer not null default 0,
  correct integer not null default 0,
  total integer not null default 0,
  attempts integer not null default 0,
  answers jsonb not null default '{}',
  history jsonb not null default '[]',
  at bigint not null,
  primary key (user_id, exam_id)
);

-- ملاحظة: أُضيف عمودا code و versions ليُخزَّن محتوى الكود في قاعدة البيانات
-- (الواجهة تقرأ file.code و file.versions للعرض والتحرير).
-- تيليجرام يبقى مرآة أحادية الاتجاه للنسخ الاحتياطي فقط (telegram_meta يحفظ موقع المرآة).
create table if not exists public.code_files (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  name text not null default 'ملف جديد',
  language text not null default 'javascript',
  code text not null default '',
  versions jsonb not null default '[]',
  telegram_meta jsonb,
  created_at bigint not null,
  updated_at bigint not null
);

create table if not exists public.app_config (
  key text primary key,
  value jsonb not null
);

-- فهارس
create index if not exists idx_lessons_course_id   on public.lessons(course_id);
create index if not exists idx_exams_course_id     on public.exams(course_id);
create index if not exists idx_questions_exam_id   on public.questions(exam_id);
create index if not exists idx_notes_course_id     on public.notes(course_id);
create index if not exists idx_progress_user_id    on public.progress(user_id);
create index if not exists idx_exam_results_user_id on public.exam_results(user_id);
create index if not exists idx_code_files_user_id  on public.code_files(user_id);

-- دالة مساعدة لسكريبت الترحيل: تعيد ضبط عداد التسلسل بعد إدراج صفوف بمعرّفات صريحة
create or replace function public._dr_reset_seq(tbl text)
returns void
language plpgsql
as $$
declare
  seq_name text;
begin
  select pg_get_serial_sequence('public.' || tbl, 'id') into seq_name;
  if seq_name is not null then
    execute format('select setval(%L, coalesce((select max(id) from public.%I), 1), true)', seq_name, tbl);
  end if;
end;
$$;
