-- ============ DR Code — Password Reset Requests ============
-- جدول طلبات تغيير كلمة السر:
-- الطالب يطلب برقمه → يخبر الإدارة (واتساب) لعرض الطلب → الإدارة توافق/ترفض
-- → عند الموافقة تظهر صفحة كتابة كلمة السر الجديدة.
-- الحالات: pending (بانتظار الإدارة) / approved (موافَق عليه) / completed (أنُجز) / rejected (مرفوض).

create table if not exists public.password_resets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending',
  created_at bigint not null,
  updated_at bigint not null
);

create index if not exists idx_password_resets_user_id on public.password_resets(user_id);
create index if not exists idx_password_resets_status on public.password_resets(status);

-- ===== RLS: نفس سياسة بقية الجداول (الوصول عبر الدالات فقط) =====
alter table public.password_resets enable row level security;

drop policy if exists "deny all anon" on public.password_resets;
drop policy if exists "deny all authenticated" on public.password_resets;
create policy "deny all anon" on public.password_resets for all to anon using (false) with check (false);
create policy "deny all authenticated" on public.password_resets for all to authenticated using (false) with check (false);